spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_scourse
    username: root
    password: 1111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
server:
  port: 8001